namespace Mugi.Json;

/// <summary>
/// Serializes and deserializes <typeparamref name="T"/> as JSON. Implementations are
/// generated by the Mugi source generator or mugi-gen, or written by hand and
/// registered with <see cref="Json.Register{T}(IJsonCodec{T})"/>.
/// </summary>
public interface IJsonCodec<T>
{
    void Write(ref JsonWriter writer, T? value);
    T? Read(ref JsonReader reader);
}
