namespace Miya.Json;

/// <summary>
/// Serializes and deserializes <typeparamref name="T"/> as JSON. Implementations are
/// generated by the Miya source generator or miya-gen, or written by hand and
/// registered with <see cref="MiyaJson.Register{T}(IMiyaJsonCodec{T})"/>.
/// </summary>
public interface IMiyaJsonCodec<T>
{
    void Write(ref MiyaJsonWriter writer, T? value);
    T? Read(ref MiyaJsonReader reader);
}
