<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <RootNamespace Condition="'$(RootNamespace)' == ''">$(MSBuildProjectName)</RootNamespace>
    <Authors>hckaye</Authors>
    <Version>0.1.2</Version>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/hckaye/Mugi</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageProjectUrl>https://github.com/hckaye/Mugi</PackageProjectUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageReadmeSource>$(MSBuildThisFileDirectory)README.md</PackageReadmeSource>
    <PackageReadmeSource Condition="Exists('$(MSBuildProjectDirectory)/README.md')">$(MSBuildProjectDirectory)/README.md</PackageReadmeSource>
  </PropertyGroup>

  <ItemGroup>
    <None Include="$(PackageReadmeSource)"
          Pack="true"
          PackagePath=""
          Visible="false" />
  </ItemGroup>
</Project>
