<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.14.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="fixtures/**/*.cs" />
    <Compile Remove="packaging/**/*.cs" />
    <None Include="fixtures/**/*" />
    <None Update="fixtures/OpenApiImport/openapi.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Miya.Generators\Miya.Generators.csproj" />
    <ProjectReference Include="..\..\src\Miya.Json\Miya.Json.csproj" />
    <ProjectReference Include="..\..\src\Miya.Schema\Miya.Schema.csproj" />
    <ProjectReference Include="..\..\src\Miya\Miya.csproj" />
  </ItemGroup>

</Project>
