using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Globalization;
using System.Linq;
using System.Text;
using System.Threading;

namespace Mugi.Generators.Core;

internal static class OpenApiClientGenerator
{
    internal static GenerationResult Generate(
        OpenApiImportInput input,
        CancellationToken cancellationToken) =>
        Generate(input, cancellationToken, emitApiException: true);

    internal static GenerationResult Generate(
        OpenApiImportInput input,
        CancellationToken cancellationToken,
        bool emitApiException)
    {
        if (input is null)
        {
            throw new ArgumentNullException(nameof(input));
        }
        var build = OpenApiImportGenerator.BuildDocument(
            input,
            cancellationToken,
            OpenApiGenerationMode.Client);
        if (build.Document is null)
        {
            return new GenerationResult(
                ImmutableArray<GeneratedSource>.Empty,
                build.Diagnostics);
        }

        var clientName = GetClientName(input, build.Document);
        var source = EmitClient(
            build.Document,
            clientName,
            emitApiException,
            GeneratedNaming.StableIdentifier("OpenApiJsonGeneratedRegistration_", clientName),
            clientName);
        var hintName = GeneratedNaming.StableIdentifier("Mugi.OpenApiClient.", input.Path) + ".g.cs";
        return new GenerationResult(
            ImmutableArray.Create(new GeneratedSource(hintName, source)),
            build.Diagnostics);
    }

    internal static GeneratedSource EmitApiExceptionSource(string targetNamespace)
    {
        var writer = new CodeWriter();
        writer.Line("// <auto-generated/>");
        writer.Line("#nullable enable");
        writer.Line();
        writer.Open("namespace " + targetNamespace);
        EmitApiException(writer);
        writer.Close();
        return new GeneratedSource(
            GeneratedNaming.StableIdentifier("Mugi.OpenApiClient.ApiException.", targetNamespace) + ".g.cs",
            writer.ToString());
    }

    private static string EmitClient(
        OpenApiImportDocument document,
        string clientName,
        bool emitApiException,
        string registrationName,
        string codecPrefix)
    {
        var writer = new CodeWriter();
        writer.Line("// <auto-generated/>");
        writer.Line("#nullable enable");
        writer.Line();
        writer.Open("namespace " + document.TargetNamespace);

        foreach (var declaration in document.Declarations
                     .OrderBy(static declaration => declaration.Name, StringComparer.Ordinal))
        {
            if (document.ReuseComponentDeclarations
                && document.ComponentTypeNames.Contains(declaration.Name))
            {
                continue;
            }

            OpenApiCodeEmitter.EmitDeclaration(writer, declaration, avoidDuplicateNullable: true);
            writer.Line();
        }

        if (emitApiException)
        {
            EmitApiException(writer);
            writer.Line();
        }

        EmitClientClass(writer, document, clientName, registrationName);
        writer.Line();

        var codecModels = new OpenApiJsonCodecModelBuilder(
            document.TargetNamespace,
            codecPrefix).Build(document);
        new OpenApiJsonSourceEmitter(codecModels).Emit(writer, registrationName);
        writer.Close();
        return writer.ToString();
    }

    private static void EmitApiException(CodeWriter writer)
    {
        writer.Open("public sealed class ApiException : global::System.Exception");
        writer.Line(
            "internal ApiException(int status, string? body) : base(\"The HTTP response was not successful.\")");
        writer.Line("{");
        writer.Line("    Status = status;");
        writer.Line("    Body = body;");
        writer.Line("}");
        writer.Line();
        writer.Line("public int Status { get; }");
        writer.Line();
        writer.Line("public string? Body { get; }");
        writer.Close();
    }

    private static void EmitClientClass(
        CodeWriter writer,
        OpenApiImportDocument document,
        string clientName,
        string registrationName)
    {
        writer.Open("public sealed class " + clientName);
        writer.Line("private readonly global::System.Net.Http.HttpClient _http;");
        writer.Line();
        writer.Open("public " + clientName + "(global::System.Net.Http.HttpClient http)");
        writer.Line("global::System.ArgumentNullException.ThrowIfNull(http);");
        writer.Line(registrationName + ".EnsureRegistered();");
        writer.Line("_http = http;");
        writer.Close();

        foreach (var operation in document.ClientOperations
                     .OrderBy(static operation => operation.Name, StringComparer.Ordinal))
        {
            writer.Line();
            EmitOperation(writer, document, operation);
        }

        writer.Close();
    }

    private static void EmitOperation(
        CodeWriter writer,
        OpenApiImportDocument document,
        OpenApiClientOperation operation)
    {
        var pathParameters = operation.Parameters
            .Where(static parameter => parameter.Source == "Route")
            .ToArray();
        var requiredParameters = operation.Parameters
            .Where(static parameter =>
                (parameter.Source == "Query" || parameter.Source == "Header") && parameter.Required)
            .ToArray();
        var optionalParameters = operation.Parameters
            .Where(static parameter =>
                (parameter.Source == "Query" || parameter.Source == "Header") && !parameter.Required)
            .ToArray();
        var bodyName = operation.BodyType is null
            ? null
            : GetBodyParameterName(operation);
        var responseType = operation.ResponseType?.Render(required: true);
        var returnType = responseType is null ? "global::System.Threading.Tasks.Task" :
            "global::System.Threading.Tasks.Task<" + responseType + ">";

        var signature = new StringBuilder();
        signature.Append("public async ");
        signature.Append(returnType);
        signature.Append(' ');
        signature.Append(operation.Name);
        signature.Append('(');
        var parameterIndex = 0;
        AppendSignatureParameters(signature, pathParameters, ref parameterIndex);
        AppendSignatureParameters(signature, requiredParameters, ref parameterIndex);
        if (operation.BodyType is not null)
        {
            if (parameterIndex++ != 0)
            {
                signature.Append(", ");
            }

            signature.Append(RenderClientType(operation.BodyType, operation.BodyRequired));
            signature.Append(' ');
            signature.Append(bodyName);
            if (!operation.BodyRequired)
            {
                signature.Append(" = null");
            }
        }

        AppendSignatureParameters(signature, optionalParameters, ref parameterIndex, optional: true);
        if (parameterIndex++ != 0)
        {
            signature.Append(", ");
        }

        signature.Append("global::System.Threading.CancellationToken cancellationToken = default)");
        writer.Open(signature.ToString());

        EmitPathParameterValidation(writer, pathParameters);
        writer.Line("var path = " + BuildPathLiteral(operation.Path, document, pathParameters) + ";");
        if (operation.Parameters.Any(static parameter => parameter.Source == "Query"))
        {
            EmitQuery(
                writer,
                document,
                operation.Parameters.Where(static parameter => parameter.Source == "Query"));
        }

        writer.Line(
            "using var request = new global::System.Net.Http.HttpRequestMessage("
            + "new global::System.Net.Http.HttpMethod("
            + GeneratedNaming.Literal(operation.Method.ToUpperInvariant()) + "), path);");
        foreach (var parameter in operation.Parameters.Where(static parameter => parameter.Source == "Header"))
        {
            var value = FormatParameterValue(parameter, document);
            if (parameter.Required)
            {
                writer.Line(
                    "request.Headers.TryAddWithoutValidation("
                    + GeneratedNaming.Literal(parameter.HeaderName!) + ", " + value + ");");
            }
            else
            {
                writer.Open("if (" + parameter.Identifier + " is not null)");
                writer.Line(
                    "request.Headers.TryAddWithoutValidation("
                    + GeneratedNaming.Literal(parameter.HeaderName!) + ", " + value + ");");
                writer.Close();
            }
        }

        if (operation.BodyType is not null)
        {
            if (operation.BodyRequired)
            {
                EmitBody(writer, bodyName!);
            }
            else
            {
                writer.Open("if (" + bodyName + " is not null)");
                EmitBody(writer, bodyName!);
                writer.Close();
            }
        }

        writer.Line(
            "using var response = await _http.SendAsync(request, cancellationToken).ConfigureAwait(false);");
        writer.Open("if (!response.IsSuccessStatusCode)");
        writer.Line(
            "var responseBytes = await response.Content.ReadAsByteArrayAsync(cancellationToken).ConfigureAwait(false);");
        writer.Line(
            "var responseBody = global::System.Text.Encoding.UTF8.GetString(responseBytes, 0, "
            + "global::System.Math.Min(responseBytes.Length, 4096));");
        writer.Line("throw new ApiException((int)response.StatusCode, responseBody);");
        writer.Close();
        if (responseType is null)
        {
            writer.Line("return;");
        }
        else
        {
            writer.Open("if (" + BuildJsonResponseCondition(operation) + ")");
            writer.Line(
                "var responseBytes = await response.Content.ReadAsByteArrayAsync(cancellationToken).ConfigureAwait(false);");
            writer.Line(
                "return global::Mugi.Json.Json.Deserialize<" + responseType + ">(responseBytes)!;");
            writer.Close();
            writer.Line("return default!;");
        }

        writer.Close();
    }

    private static void EmitPathParameterValidation(
        CodeWriter writer,
        IEnumerable<OpenApiImportProperty> pathParameters)
    {
        foreach (var parameter in pathParameters.Where(static parameter =>
                     parameter.Type.Kind == OpenApiImportTypeKind.String))
        {
            writer.Open(
                "if (global::System.String.IsNullOrEmpty(" + parameter.Identifier + ") || " +
                parameter.Identifier + " == \".\" || " + parameter.Identifier + " == \"..\")");
            writer.Line(
                "throw new global::System.ArgumentException(" +
                GeneratedNaming.Literal("Path parameters cannot be empty, '.' or '..'.") + ", " +
                "nameof(" + parameter.Identifier + "));");
            writer.Close();
        }
    }

    private static string BuildJsonResponseCondition(OpenApiClientOperation operation)
    {
        var exactStatuses = operation.JsonResponseStatuses
            .Where(static status => !string.Equals(status, "2XX", StringComparison.OrdinalIgnoreCase))
            .Select(static status => "(int)response.StatusCode == " + status)
            .ToList();
        if (operation.JsonResponseStatuses.Any(static status =>
                string.Equals(status, "2XX", StringComparison.OrdinalIgnoreCase)))
        {
            var range = "((int)response.StatusCode >= 200 && (int)response.StatusCode <= 299)";
            var exclusions = operation.NoBodyResponseStatuses
                .Where(static status => !string.Equals(status, "2XX", StringComparison.OrdinalIgnoreCase))
                .Select(static status => "(int)response.StatusCode != " + status)
                .ToArray();
            exactStatuses.Add(exclusions.Length == 0
                ? range
                : "(" + range + " && " + string.Join(" && ", exclusions) + ")");
        }

        return exactStatuses.Count == 0 ? "false" : string.Join(" || ", exactStatuses);
    }

    private static void AppendSignatureParameters(
        StringBuilder builder,
        IReadOnlyList<OpenApiImportProperty> parameters,
        ref int parameterIndex,
        bool optional = false)
    {
        foreach (var parameter in parameters)
        {
            if (parameterIndex++ != 0)
            {
                builder.Append(", ");
            }

            builder.Append(RenderClientType(parameter.Type, required: !optional));
            builder.Append(' ');
            builder.Append(parameter.Identifier);
            if (optional)
            {
                builder.Append(" = null");
            }
        }
    }

    private static void EmitQuery(
        CodeWriter writer,
        OpenApiImportDocument document,
        IEnumerable<OpenApiImportProperty> parameters)
    {
        writer.Line("var query = new global::System.Text.StringBuilder();");
        writer.Line("var hasQueryParameter = false;");
        foreach (var parameter in parameters)
        {
            if (parameter.Required)
            {
                EmitQueryAppend(writer, document, parameter);
                continue;
            }

            writer.Open("if (" + parameter.Identifier + " is not null)");
            EmitQueryAppend(writer, document, parameter);
            writer.Close();
        }

        writer.Open("if (hasQueryParameter)");
        writer.Line("path += query.ToString();");
        writer.Close();
    }

    private static void EmitQueryAppend(
        CodeWriter writer,
        OpenApiImportDocument document,
        OpenApiImportProperty parameter)
    {
        writer.Line("query.Append(hasQueryParameter ? \"&\" : \"?\");");
        writer.Line("query.Append(" + GeneratedNaming.Literal(parameter.OpenApiName) + ");");
        writer.Line("query.Append('=');");
        writer.Line(
            "query.Append(global::System.Uri.EscapeDataString("
            + FormatParameterValue(parameter, document) + "));");
        writer.Line("hasQueryParameter = true;");
    }

    private static void EmitBody(CodeWriter writer, string bodyName)
    {
        writer.Line("var bodyBuffer = new global::System.Buffers.ArrayBufferWriter<byte>();");
        writer.Line("global::Mugi.Json.Json.Serialize(bodyBuffer, " + bodyName + ");");
        writer.Line(
            "request.Content = new global::System.Net.Http.ByteArrayContent(bodyBuffer.WrittenSpan.ToArray());");
        writer.Line(
            "request.Content.Headers.ContentType = new global::System.Net.Http.Headers.MediaTypeHeaderValue("
            + GeneratedNaming.Literal("application/json") + ") { CharSet = "
            + GeneratedNaming.Literal("utf-8") + " };");
    }

    private static string BuildPathLiteral(
        string path,
        OpenApiImportDocument document,
        IReadOnlyList<OpenApiImportProperty> pathParameters)
    {
        var parameters = pathParameters.ToDictionary(
            static parameter => parameter.OpenApiName,
            static parameter => parameter,
            StringComparer.Ordinal);
        var builder = new StringBuilder("$\"");
        var segments = path.Split(new[] { '/' }, StringSplitOptions.None);
        for (var segmentIndex = 0; segmentIndex < segments.Length; segmentIndex++)
        {
            if (segmentIndex != 0)
            {
                builder.Append('/');
            }

            var segment = segments[segmentIndex];
            if (segment.StartsWith(":", StringComparison.Ordinal)
                && parameters.TryGetValue(segment.Substring(1), out var parameter))
            {
                builder.Append("{(global::System.Uri.EscapeDataString(");
                builder.Append(FormatParameterValue(parameter, document));
                builder.Append("))}");
            }
            else
            {
                AppendInterpolatedLiteral(builder, segment);
            }
        }

        builder.Append('"');
        return builder.ToString();
    }

    private static void AppendInterpolatedLiteral(StringBuilder builder, string value)
    {
        foreach (var character in value)
        {
            switch (character)
            {
                case '\\':
                    builder.Append("\\\\");
                    break;
                case '"':
                    builder.Append("\\\"");
                    break;
                case '{':
                    builder.Append("{{");
                    break;
                case '}':
                    builder.Append("}}");
                    break;
                case '\b':
                    builder.Append("\\b");
                    break;
                case '\f':
                    builder.Append("\\f");
                    break;
                case '\n':
                    builder.Append("\\n");
                    break;
                case '\r':
                    builder.Append("\\r");
                    break;
                case '\t':
                    builder.Append("\\t");
                    break;
                default:
                    if (character < ' ')
                    {
                        builder.Append("\\u");
                        builder.Append(((int)character).ToString("X4", CultureInfo.InvariantCulture));
                    }
                    else
                    {
                        builder.Append(character);
                    }

                    break;
            }
        }
    }

    private static string FormatParameterValue(
        OpenApiImportProperty parameter,
        OpenApiImportDocument document)
    {
        var identifier = parameter.Identifier;
        const string culture = "global::System.Globalization.CultureInfo.InvariantCulture";
        if (parameter.Type.Kind == OpenApiImportTypeKind.String)
        {
            return parameter.Type.Nullable || !parameter.Required
                ? identifier + " ?? string.Empty"
                : identifier;
        }

        var valueType = parameter.Type.Nullable || !parameter.Required
            ? identifier + ".Value"
            : identifier;
        if (parameter.Type.Kind == OpenApiImportTypeKind.Enum)
        {
            return FormatEnumValue(parameter, document, valueType);
        }

        if (parameter.Type.Kind == OpenApiImportTypeKind.Boolean)
        {
            return valueType + " ? \"true\" : \"false\"";
        }

        return valueType + ".ToString(" + culture + ")";
    }

    private static string FormatEnumValue(
        OpenApiImportProperty parameter,
        OpenApiImportDocument document,
        string value)
    {
        var builder = new StringBuilder();
        builder.Append(value);
        builder.Append(" switch { ");
        var declaration = document.Declarations
            .OfType<OpenApiImportEnum>()
            .FirstOrDefault(item => string.Equals(item.Name, parameter.Type.Name, StringComparison.Ordinal));
        if (declaration is not null)
        {
            foreach (var member in declaration.Members)
            {
                builder.Append(parameter.Type.Name);
                builder.Append('.');
                builder.Append(member.Value);
                builder.Append(" => ");
                builder.Append(GeneratedNaming.Literal(member.Key));
                builder.Append(", ");
            }
        }

        builder.Append("_ => ");
        builder.Append(value);
        builder.Append(".ToString() }");
        return builder.ToString();
    }

    private static string GetBodyParameterName(OpenApiClientOperation operation)
    {
        var names = new HashSet<string>(
            operation.Parameters.Select(static parameter =>
                parameter.Identifier.StartsWith("@", StringComparison.Ordinal)
                    ? parameter.Identifier.Substring(1)
                    : parameter.Identifier),
            StringComparer.Ordinal);
        var candidate = "body";
        var suffix = 2;
        while (!names.Add(candidate))
        {
            candidate = "body" + suffix++;
        }

        return candidate;
    }

    private static string RenderClientType(OpenApiImportType type, bool required) =>
        type.Nullable && !required
            ? type.Render(required: true)
            : type.Render(required);

    private static string GetClientName(OpenApiImportInput input, OpenApiImportDocument document)
    {
        var raw = string.IsNullOrWhiteSpace(input.ClientName)
            ? OpenApiImportGenerator.PublicIdentifier(document.Title ?? "OpenApi", "OpenApi") + "Client"
            : input.ClientName!;
        if (!OpenApiImportGenerator.TryExactIdentifier(raw, out var rendered))
        {
            throw new InvalidOperationException("The OpenAPI client class name is not a valid C# identifier.");
        }

        return rendered;
    }
}
