// <auto-generated/>
#nullable enable

namespace Miya.IntegrationTests.Client
{
    public sealed record CreateItemBody(
        string Name,
        string? Note);

    public sealed record Item(
        string Id,
        string Name,
        string Note);

    public sealed class ApiException : global::System.Exception
    {
        internal ApiException(int status, string? body) : base("The HTTP response was not successful.")
        {
            Status = status;
            Body = body;
        }

        public int Status { get; }

        public string? Body { get; }
    }

    public sealed class E2eClient
    {
        private readonly global::System.Net.Http.HttpClient _http;

        public E2eClient(global::System.Net.Http.HttpClient http)
        {
            global::System.ArgumentNullException.ThrowIfNull(http);
            OpenApiJsonGeneratedRegistration_E2eClient.EnsureRegistered();
            _http = http;
        }

        public async global::System.Threading.Tasks.Task<Item> CreateItem(CreateItemBody body, global::System.Threading.CancellationToken cancellationToken = default)
        {
            var path = $"/items";
            using var request = new global::System.Net.Http.HttpRequestMessage(new global::System.Net.Http.HttpMethod("POST"), path);
            var bodyBuffer = new global::System.Buffers.ArrayBufferWriter<byte>();
            global::Miya.Json.Json.Serialize(bodyBuffer, body);
            request.Content = new global::System.Net.Http.ByteArrayContent(bodyBuffer.WrittenSpan.ToArray());
            request.Content.Headers.ContentType = new global::System.Net.Http.Headers.MediaTypeHeaderValue("application/json") { CharSet = "utf-8" };
            using var response = await _http.SendAsync(request, cancellationToken).ConfigureAwait(false);
            if (!response.IsSuccessStatusCode)
            {
                var responseBytes = await response.Content.ReadAsByteArrayAsync(cancellationToken).ConfigureAwait(false);
                var responseBody = global::System.Text.Encoding.UTF8.GetString(responseBytes, 0, global::System.Math.Min(responseBytes.Length, 4096));
                throw new ApiException((int)response.StatusCode, responseBody);
            }
            if ((int)response.StatusCode == 201)
            {
                var responseBytes = await response.Content.ReadAsByteArrayAsync(cancellationToken).ConfigureAwait(false);
                return global::Miya.Json.Json.Deserialize<Item>(responseBytes)!;
            }
            return default!;
        }

        public async global::System.Threading.Tasks.Task<Item> GetItem(string id, string? note = null, global::System.Threading.CancellationToken cancellationToken = default)
        {
            if (global::System.String.IsNullOrEmpty(id) || id == "." || id == "..")
            {
                throw new global::System.ArgumentException("Path parameters cannot be empty, '.' or '..'.", nameof(id));
            }
            var path = $"/items/{(global::System.Uri.EscapeDataString(id))}";
            var query = new global::System.Text.StringBuilder();
            var hasQueryParameter = false;
            if (note is not null)
            {
                query.Append(hasQueryParameter ? "&" : "?");
                query.Append("note");
                query.Append('=');
                query.Append(global::System.Uri.EscapeDataString(note ?? string.Empty));
                hasQueryParameter = true;
            }
            if (hasQueryParameter)
            {
                path += query.ToString();
            }
            using var request = new global::System.Net.Http.HttpRequestMessage(new global::System.Net.Http.HttpMethod("GET"), path);
            using var response = await _http.SendAsync(request, cancellationToken).ConfigureAwait(false);
            if (!response.IsSuccessStatusCode)
            {
                var responseBytes = await response.Content.ReadAsByteArrayAsync(cancellationToken).ConfigureAwait(false);
                var responseBody = global::System.Text.Encoding.UTF8.GetString(responseBytes, 0, global::System.Math.Min(responseBytes.Length, 4096));
                throw new ApiException((int)response.StatusCode, responseBody);
            }
            if ((int)response.StatusCode == 200)
            {
                var responseBytes = await response.Content.ReadAsByteArrayAsync(cancellationToken).ConfigureAwait(false);
                return global::Miya.Json.Json.Deserialize<Item>(responseBytes)!;
            }
            return default!;
        }
    }

    internal sealed class E2eClient_Codec_005F_0_003A__003A_R : global::Miya.Json.IJsonCodec<string>
    {
        internal static readonly E2eClient_Codec_005F_0_003A__003A_R Instance = new E2eClient_Codec_005F_0_003A__003A_R();

        public void Write(ref global::Miya.Json.JsonWriter writer, string? value) => WriteValue(ref writer, value);
        public string? Read(ref global::Miya.Json.JsonReader reader) => ReadValue(ref reader, 0);

        internal static void WriteValue(ref global::Miya.Json.JsonWriter writer, string? value)
        {
            writer.WriteString(value);
        }

        internal static string? ReadValue(ref global::Miya.Json.JsonReader reader, int depth)
        {
            return reader.ReadString();
        }
    }

    internal sealed class E2eClient_Codec_005F_named_003A_CreateItemBody : global::Miya.Json.IJsonCodec<global::Miya.IntegrationTests.Client.CreateItemBody>
    {
        internal static readonly E2eClient_Codec_005F_named_003A_CreateItemBody Instance = new E2eClient_Codec_005F_named_003A_CreateItemBody();

        public void Write(ref global::Miya.Json.JsonWriter writer, global::Miya.IntegrationTests.Client.CreateItemBody? value) => WriteValue(ref writer, value);
        public global::Miya.IntegrationTests.Client.CreateItemBody? Read(ref global::Miya.Json.JsonReader reader) => ReadValue(ref reader, 0);

        internal static void WriteValue(ref global::Miya.Json.JsonWriter writer, global::Miya.IntegrationTests.Client.CreateItemBody? value)
        {
            if (value is null)
            {
                writer.WriteNull();
                return;
            }
            writer.EnterContainer(2);
            writer.WriteRaw("{\"name\":"u8);
            E2eClient_Codec_005F_0_003A__003A_R.WriteValue(ref writer, value.Name);
            writer.WriteRaw(",\"note\":"u8);
            E2eClient_Codec_005F_0_003A__003A_R.WriteValue(ref writer, value.Note);
            writer.WriteRaw("}"u8);
            writer.ExitContainer();
        }

        internal static global::Miya.IntegrationTests.Client.CreateItemBody? ReadValue(ref global::Miya.Json.JsonReader reader, int depth)
        {
            if (reader.TryReadNull())
            {
                return null;
            }
            string property0 = default!;
            var hasProperty0 = false;
            string? property1 = default!;
            reader.ReadBeginObject();
            while (!reader.TryReadEndObject())
            {
                var propertyName = reader.ReadPropertyName();
                switch (propertyName.Length)
                {
                    case 4:
                    if (global::System.MemoryExtensions.SequenceEqual(propertyName, "name"u8))
                    {
                        property0 = E2eClient_Codec_005F_0_003A__003A_R.ReadValue(ref reader, depth + 1) ?? throw new global::Miya.Json.JsonException("Property 'name' cannot be null.", isInputError: true);
                        hasProperty0 = true;
                    }
                    else if (global::System.MemoryExtensions.SequenceEqual(propertyName, "note"u8))
                    {
                        property1 = E2eClient_Codec_005F_0_003A__003A_R.ReadValue(ref reader, depth + 1);
                    }
                    else
                    {
                        reader.SkipValue();
                    }
                    break;
                    default:
                        reader.SkipValue();
                        break;
                }
            }
            if (!hasProperty0)
            {
                throw new global::Miya.Json.JsonException("Required property 'name' is missing for 'global::Miya.IntegrationTests.Client.CreateItemBody'.", isInputError: true);
            }
            return new global::Miya.IntegrationTests.Client.CreateItemBody(property0, property1);
        }
    }

    internal sealed class E2eClient_Codec_005F_named_003A_Item : global::Miya.Json.IJsonCodec<global::Miya.IntegrationTests.Client.Item>
    {
        internal static readonly E2eClient_Codec_005F_named_003A_Item Instance = new E2eClient_Codec_005F_named_003A_Item();

        public void Write(ref global::Miya.Json.JsonWriter writer, global::Miya.IntegrationTests.Client.Item? value) => WriteValue(ref writer, value);
        public global::Miya.IntegrationTests.Client.Item? Read(ref global::Miya.Json.JsonReader reader) => ReadValue(ref reader, 0);

        internal static void WriteValue(ref global::Miya.Json.JsonWriter writer, global::Miya.IntegrationTests.Client.Item? value)
        {
            if (value is null)
            {
                writer.WriteNull();
                return;
            }
            writer.EnterContainer(3);
            writer.WriteRaw("{\"id\":"u8);
            E2eClient_Codec_005F_0_003A__003A_R.WriteValue(ref writer, value.Id);
            writer.WriteRaw(",\"name\":"u8);
            E2eClient_Codec_005F_0_003A__003A_R.WriteValue(ref writer, value.Name);
            writer.WriteRaw(",\"note\":"u8);
            E2eClient_Codec_005F_0_003A__003A_R.WriteValue(ref writer, value.Note);
            writer.WriteRaw("}"u8);
            writer.ExitContainer();
        }

        internal static global::Miya.IntegrationTests.Client.Item? ReadValue(ref global::Miya.Json.JsonReader reader, int depth)
        {
            if (reader.TryReadNull())
            {
                return null;
            }
            string property0 = default!;
            var hasProperty0 = false;
            string property1 = default!;
            var hasProperty1 = false;
            string property2 = default!;
            var hasProperty2 = false;
            reader.ReadBeginObject();
            while (!reader.TryReadEndObject())
            {
                var propertyName = reader.ReadPropertyName();
                switch (propertyName.Length)
                {
                    case 2:
                    if (global::System.MemoryExtensions.SequenceEqual(propertyName, "id"u8))
                    {
                        property0 = E2eClient_Codec_005F_0_003A__003A_R.ReadValue(ref reader, depth + 1) ?? throw new global::Miya.Json.JsonException("Property 'id' cannot be null.", isInputError: true);
                        hasProperty0 = true;
                    }
                    else
                    {
                        reader.SkipValue();
                    }
                    break;
                    case 4:
                    if (global::System.MemoryExtensions.SequenceEqual(propertyName, "name"u8))
                    {
                        property1 = E2eClient_Codec_005F_0_003A__003A_R.ReadValue(ref reader, depth + 1) ?? throw new global::Miya.Json.JsonException("Property 'name' cannot be null.", isInputError: true);
                        hasProperty1 = true;
                    }
                    else if (global::System.MemoryExtensions.SequenceEqual(propertyName, "note"u8))
                    {
                        property2 = E2eClient_Codec_005F_0_003A__003A_R.ReadValue(ref reader, depth + 1) ?? throw new global::Miya.Json.JsonException("Property 'note' cannot be null.", isInputError: true);
                        hasProperty2 = true;
                    }
                    else
                    {
                        reader.SkipValue();
                    }
                    break;
                    default:
                        reader.SkipValue();
                        break;
                }
            }
            if (!hasProperty0)
            {
                throw new global::Miya.Json.JsonException("Required property 'id' is missing for 'global::Miya.IntegrationTests.Client.Item'.", isInputError: true);
            }
            if (!hasProperty1)
            {
                throw new global::Miya.Json.JsonException("Required property 'name' is missing for 'global::Miya.IntegrationTests.Client.Item'.", isInputError: true);
            }
            if (!hasProperty2)
            {
                throw new global::Miya.Json.JsonException("Required property 'note' is missing for 'global::Miya.IntegrationTests.Client.Item'.", isInputError: true);
            }
            return new global::Miya.IntegrationTests.Client.Item(property0, property1, property2);
        }
    }


    internal static class OpenApiJsonGeneratedRegistration_E2eClient
    {
        static OpenApiJsonGeneratedRegistration_E2eClient()
        {
            global::Miya.Json.Json.Register<string>(global::Miya.Json.Json.ResolveCodec<string>(E2eClient_Codec_005F_0_003A__003A_R.Instance));
            global::Miya.Json.Json.Register<global::Miya.IntegrationTests.Client.CreateItemBody>(global::Miya.Json.Json.ResolveCodec<global::Miya.IntegrationTests.Client.CreateItemBody>(E2eClient_Codec_005F_named_003A_CreateItemBody.Instance));
            global::Miya.Json.Json.Register<global::Miya.IntegrationTests.Client.Item>(global::Miya.Json.Json.ResolveCodec<global::Miya.IntegrationTests.Client.Item>(E2eClient_Codec_005F_named_003A_Item.Instance));
        }

        internal static void EnsureRegistered()
        {
        }
    }
}
