using System;
using System.Collections.Immutable;
using Microsoft.CodeAnalysis;

namespace Miya.Generators.Core;

internal sealed class JsonSourceEmitter
{
    private readonly ImmutableArray<JsonTypeModel> _models;
    private readonly GeneratorSettings _settings;

    internal JsonSourceEmitter(ImmutableArray<JsonTypeModel> models, GeneratorSettings settings)
    {
        _models = models;
        _settings = settings;
    }

    internal string EmitCodecs()
    {
        var writer = StartFile();
        var models = AdaptModels();
        new JsonCodecSourceEmitter(models).EmitCodecs(writer);
        return writer.ToString();
    }

    internal string EmitCodecAndRegistrationSource(JsonTypeModel model)
    {
        var writer = StartFile();
        var models = AdaptModels();
        var adaptedModel = FindModel(model, models);
        var emitter = new JsonCodecSourceEmitter(models);
        emitter.EmitCodec(writer, adaptedModel);
        writer.Line();
        emitter.EmitSingleRegistration(
            writer,
            adaptedModel,
            "JsonGeneratedRegistration_" + adaptedModel.CodecName);
        return writer.ToString();
    }

    internal string EmitRegistration()
    {
        var writer = StartFile();
        var models = AdaptModels();
        new JsonCodecSourceEmitter(models).EmitRegistration(writer, "JsonGeneratedRegistration");
        return writer.ToString();
    }

    private ImmutableArray<IJsonCodecModel> AdaptModels() =>
        RoslynJsonCodecModelAdapter.Create(_models, _settings);

    private static IJsonCodecModel FindModel(
        JsonTypeModel model,
        ImmutableArray<IJsonCodecModel> adaptedModels)
    {
        for (var index = 0; index < adaptedModels.Length; index++)
        {
            if (adaptedModels[index] is RoslynJsonCodecModelAdapter adapted
                && SymbolEqualityComparer.Default.Equals(model.Type, adapted.Symbol))
            {
                return adapted;
            }
        }

        throw new InvalidOperationException("The JSON codec model was not adapted.");
    }

    private static CodeWriter StartFile()
    {
        var writer = new CodeWriter();
        writer.Line("// <auto-generated/>");
        writer.Line("#nullable enable");
        writer.Line();
        writer.Line("namespace Miya.Generated;");
        writer.Line();
        return writer;
    }
}
