<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsAotCompatible>true</IsAotCompatible>
    <PackageId>Miya</PackageId>
    <Description>A fast, simple web application framework for .NET 10, built for Native AOT.</Description>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="../Miya.Json/Miya.Json.csproj" />
  </ItemGroup>

</Project>
